# Generated by Django 5.0.7 on 2024-08-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorData',
            fields=[
                ('instructor_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructor_data',
            },
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('student_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_data',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_data',
        ),
    ]
